"""empty message

Revision ID: e6e803f959af
Revises: dde24bfed677
Create Date: 2020-04-13 15:45:04.192069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e803f959af'
down_revision = 'dde24bfed677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('program', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1200), nullable=False),
    sa.ForeignKeyConstraint(['program'], ['program.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('exercise')
    op.drop_table('workout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('program', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1200), nullable=False),
    sa.ForeignKeyConstraint(['program'], ['program.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercise',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('workout', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=300), nullable=False),
    sa.Column('frequency_lower', sa.INTEGER(), nullable=True),
    sa.Column('frequency_upper', sa.INTEGER(), nullable=True),
    sa.Column('completetion_type', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('task')
    # ### end Alembic commands ###
